### PR TITLE
Update some dependencies

### PR DESCRIPTION
**Pull request by jwodder**

### CODE REVIEW

**Comment by jwodder** [comment]
@yarikoptic Did something about the `DANDI_API_KEY` secret used to authenticate with staging change a couple weeks ago?  Recent tests in CI have been failing with "401 Unauthorized" errors.

**Comment by yarikoptic** [comment]
tests are failing, didn't check if due to changes

**Comment by yarikoptic** [comment]
> @yarikoptic Did something about the `DANDI_API_KEY` secret used to authenticate with staging change a couple weeks ago? Recent tests in CI have been failing with "401 Unauthorized" errors.

oh, if it was "mine" -- I think I have regenerated it!   Let me update it... (will look into registering with dandibot...)

**Comment by yarikoptic** [comment]
I have updated to a new key, now associated with dandibot account.

**Comment by jwodder** [comment]
@yarikoptic Secret updated.

**Comment by jwodder** [comment]
@yarikoptic Now the tests are getting "403 Forbidden" when trying to delete Dandiset versions (Does that require admin privileges?).

**Comment by yarikoptic** [comment]
correct!  only admin can delete released versions. Please re-try now ;)

**Comment by jwodder** [comment]
@yarikoptic Tests pass now.

**Pull request merged**
