### PR TITLE
Update backups2datalad.py to use dandi-api

### LINKED ISSUE #36: backups2datalad.py: RF to use dandi-api not girder
migration is upon us, so time to have this script migrate to use dandi-api interface and URLs
- overall scope: replace interactions with girder instance with interactions with dandi-api
  - https://gui-beta-dandiarchive-org.netlify.app/#/dandiset still has some datasets populated so would work, but I think it is worthwhile to:
  - add basic testing on a dockerized instance (setup similar or may be even could reuse dandi-cli ?) where we 
    - create dandiset
    - populate with sample data
    - populate/create datalad dataset
    - update sample dandiset
    - see if update works out as expected
- URLs to add:
  - I think we should populate two URLs:
    - dandi-api endpoint (assets are no longer mutable so should be ok): `/dandisets/{versions__dandiset__pk}/versions/{versions__version}/assets/{asset_id}/download/`
    - direct url to S3 `blobs/` store

Later: 
- I left prior #34 as is for now.  We might handle that one later as "remove girder URLs" script

### PR DESCRIPTION
**Pull request by jwodder**
Closes #36.

### CODE REVIEW

**Comment by yarikoptic** [comment]
Hi @jwodder ! Now that all data is migrated to dandi-api instance, could you please give this tune up a shot (as dandi@drogon) on e.g. 000027 and then e.g. 000029.  AFAIK there should be no changes needed to be committed.  Then add (and/or rename, remove) some file to 000029 and see if change gets reflected correctly.

**Comment by jwodder** [comment]
@yarikoptic The API is not yet returning SHA256 digests in asset metadata.  What should be done about that?

**Comment by yarikoptic** [comment]
Just compute etag if no sha256 is provided as discussed in https://github.com/dandi/dandisets/issues/36#issuecomment-823492172

**Comment by jwodder** [comment]
@yarikoptic I'm getting "Connection closed by remote host" when trying to log into drogon, even when connected to the Dartmouth VPN.  My IP address outside of the VPN is currently 24.0.48.55.

> Then add (and/or rename, remove) some file to 000029 and see if change gets reflected correctly.

Do you mean add a file to the Dandiset on Dandiarchive or add a file to the local dataset on drogon?

**Comment by jwodder** [comment]
@yarikoptic There actually were [changes committed](https://github.com/dandisets/000027/commit/bcecdce98758c31de8882ecda552bd060dc3fa25) when run on 000027: the `assets.json` and `dandiset.yaml` files were both updated due to changes in metadata.

**Comment by jwodder** [comment]
@yarikoptic After adding a file to 000029, the script fails upon trying to add the dandi-api `.../download/` URL to the file with the following error:

```
datalad.support.exceptions.AnnexBatchCommandError: AnnexBatchCommandError: 'addurl' [Error, annex reported failure for addurl (url='https://api.dandiarchive.org/api/dandisets/000029/versions/draft/assets/6b1f223b-5411-43d8-badb-cf23186c24ed/download/'): {'command': 'addurl', 'success': False, 'input': ['https://api.dandiarchive.org/api/dandisets/000029/versions/draft/assets/6b1f223b-5411-43d8-badb-cf23186c24ed/download/ test.txt'], 'error-messages': ['  test.txt already exists; not overwriting'], 'file': 'test.txt'}]
```

Does datalad and/or git-annex not support adding more than one URL to a file?

**Comment by yarikoptic** [comment]
re addurl: yes, for an existing file you would need to use `annex registerurl` e.g. via `ds.repo.call_annex(["registerurl", key, url])`.   
 There is `ds.repo.get_file_key` to get key(s) for file(s). May be datalad's `addurls` could be used to "streamline" adding urls but not sure.

**Comment by jwodder** [comment]
@yarikoptic The script seems to be working correctly now.

**Comment by yarikoptic** [comment]
sweet!  shouldn't it register new urls?  I am looking at 
```
(dandisets) dandi@drogon:/mnt/backup/dandi/dandisets/000027$ git annex whereis  sub-RAT123/sub-RAT123.nwb whereis sub-RAT123/sub-RAT123.nwb (2 copies) 
        00000000-0000-0000-0000-000000000001 -- web
        4ca7c743-c5d4-4e57-8ba7-ca3dc579591d -- dandi@drogon:/mnt/backup/dandi/dandisets/000027 [here]

  The following untrusted locations may also have copies:
        727f466f-60c3-4778-90b2-b2332856c2f8 -- [dandi-dandisets-dropbox]

  web: https://dandiarchive.s3.amazonaws.com/girder-assetstore/74/0f/740feade0d784acc8ec76bb7834d80dc?versionId=Y3wgHpkkLNI2NwEZH_cG6B0MPpc7eRb_
ok
```
so there is only old girder url.  I guess they are added only to new files. (and text.txt in 29 is text, so went directly to git).

I will try it on 000003 now, and if all good - sweep across.  I guess populating with `/blobs` urls for existing files could be done later, and may be just as a dedicated command/function so we do not bother checking all old files all the time.

**Comment by yarikoptic** [comment]
I have done a full pass with this script

<details>
<summary>datalad diff -r before saving super dataset</summary> 

```shell
(dandisets) dandi@drogon:/mnt/backup/dandi/dandisets$ datalad diff -r
 modified: 000003 (dataset)
 modified: 000003/.dandi/assets.json (file)
 modified: 000003/dandiset.yaml (file)
 modified: 000004 (dataset)
 modified: 000004/.dandi/assets.json (file)
 modified: 000004/dandiset.yaml (file)
 modified: 000005 (dataset)
 modified: 000005/.dandi/assets.json (file)
 modified: 000005/dandiset.yaml (file)
 modified: 000006 (dataset)
 modified: 000006/.dandi/assets.json (file)
 modified: 000006/dandiset.yaml (file)
 modified: 000007 (dataset)
 modified: 000007/.dandi/assets.json (file)
 modified: 000007/dandiset.yaml (file)
 modified: 000008 (dataset)
 modified: 000008/.dandi/assets.json (file)
 modified: 000008/dandiset.yaml (file)
 modified: 000009 (dataset)
 modified: 000009/.dandi/assets.json (file)
 modified: 000009/dandiset.yaml (file)
 modified: 000010 (dataset)
 modified: 000010/.dandi/assets.json (file)
 modified: 000010/dandiset.yaml (file)
 modified: 000011 (dataset)
 modified: 000011/.dandi/assets.json (file)
 modified: 000011/dandiset.yaml (file)
 modified: 000012 (dataset)
 modified: 000012/.dandi/assets.json (file)
 modified: 000012/dandiset.yaml (file)
 modified: 000013 (dataset)
 modified: 000013/.dandi/assets.json (file)
 modified: 000013/dandiset.yaml (file)
 modified: 000015 (dataset)
 modified: 000015/.dandi/assets.json (file)
 modified: 000015/dandiset.yaml (file)
 modified: 000016 (dataset)
 modified: 000016/.dandi/assets.json (file)
 modified: 000016/dandiset.yaml (file)
 modified: 000017 (dataset)
 modified: 000017/.dandi/assets.json (file)
 modified: 000017/dandiset.yaml (file)
 modified: 000018 (dataset)
 modified: 000018/dandiset.yaml (file)
 modified: 000019 (dataset)
 modified: 000019/.dandi/assets.json (file)
 modified: 000019/dandiset.yaml (file)
 modified: 000020 (dataset)
 modified: 000020/.dandi/assets.json (file)
 modified: 000020/dandiset.yaml (file)
 modified: 000021 (dataset)
 modified: 000021/.dandi/assets.json (file)
 modified: 000021/dandiset.yaml (file)
 modified: 000022 (dataset)
 modified: 000022/.dandi/assets.json (file)
 modified: 000022/dandiset.yaml (file)
 modified: 000023 (dataset)
 modified: 000023/.dandi/assets.json (file)
 modified: 000023/dandiset.yaml (file)
 modified: 000024 (dataset)
 modified: 000024/dandiset.yaml (file)
 modified: 000025 (dataset)
 modified: 000025/.dandi/assets.json (file)
 modified: 000025/dandiset.yaml (file)
 modified: 000026 (dataset)
 modified: 000026/.dandi/assets.json (file)
 modified: 000026/dandiset.yaml (file)
 modified: 000027 (dataset)
 modified: 000027/.dandi/assets.json (file)
 modified: 000028 (dataset)
 modified: 000028/.dandi/assets.json (file)
 modified: 000028/dandiset.yaml (file)
 modified: 000029 (dataset)
 modified: 000029/.dandi/assets.json (file)
    added: 000029/123.dat (file)
  deleted: 000029/test.txt (file)
 modified: 000030 (dataset)
 modified: 000030/dandiset.yaml (file)
 modified: 000031 (dataset)
 modified: 000031/dandiset.yaml (file)
 modified: 000032 (dataset)
 modified: 000032/dandiset.yaml (file)
 modified: 000033 (dataset)
 modified: 000033/dandiset.yaml (file)
 modified: 000034 (dataset)
 modified: 000034/.dandi/assets.json (file)
 modified: 000034/dandiset.yaml (file)
 modified: 000035 (dataset)
 modified: 000035/.dandi/assets.json (file)
 modified: 000035/dandiset.yaml (file)
 modified: 000036 (dataset)
 modified: 000036/.dandi/assets.json (file)
 modified: 000036/dandiset.yaml (file)
 modified: 000037 (dataset)
 modified: 000037/.dandi/assets.json (file)
 modified: 000037/dandiset.yaml (file)
 modified: 000038 (dataset)
 modified: 000038/dandiset.yaml (file)
 modified: 000039 (dataset)
 modified: 000039/.dandi/assets.json (file)
 modified: 000039/dandiset.yaml (file)
 modified: 000040 (dataset)
 modified: 000040/dandiset.yaml (file)
 modified: 000041 (dataset)
 modified: 000041/.dandi/assets.json (file)
 modified: 000041/dandiset.yaml (file)
 modified: 000042 (dataset)
 modified: 000042/dandiset.yaml (file)
 modified: 000043 (dataset)
 modified: 000043/.dandi/assets.json (file)
 modified: 000043/dandiset.yaml (file)
 modified: 000044 (dataset)
 modified: 000044/.dandi/assets.json (file)
 modified: 000044/dandiset.yaml (file)
 modified: 000045 (dataset)
 modified: 000045/.dandi/assets.json (file)
 modified: 000045/dandiset.yaml (file)
 modified: 000046 (dataset)
 modified: 000046/dandiset.yaml (file)
 modified: 000047 (dataset)
 modified: 000047/dandiset.yaml (file)
 modified: 000048 (dataset)
 modified: 000048/.dandi/assets.json (file)
 modified: 000048/dandiset.yaml (file)
 modified: 000049 (dataset)
 modified: 000049/.dandi/assets.json (file)
 modified: 000049/dandiset.yaml (file)
 modified: 000050 (dataset)
 modified: 000050/.dandi/assets.json (file)
 modified: 000050/dandiset.yaml (file)
 modified: 000051 (dataset)
 modified: 000051/.dandi/assets.json (file)
 modified: 000051/dandiset.yaml (file)
 modified: 000052 (dataset)
 modified: 000052/.dandi/assets.json (file)
 modified: 000052/dandiset.yaml (file)
 modified: 000053 (dataset)
 modified: 000053/dandiset.yaml (file)
 modified: 000053/sub-npI1/sub-npI1_ses-20190413_behavior+ecephys.nwb (file)
 modified: 000054 (dataset)
 modified: 000054/.dandi/assets.json (file)
 modified: 000054/dandiset.yaml (file)
 modified: 000055 (dataset)
 modified: 000055/.dandi/assets.json (file)
 modified: 000055/dandiset.yaml (file)
 modified: 000056 (dataset)
 modified: 000056/.dandi/assets.json (file)
 modified: 000056/dandiset.yaml (file)
 modified: 000057 (dataset)
 modified: 000057/dandiset.yaml (file)
 modified: 000058 (dataset)
 modified: 000058/dandiset.yaml (file)
 modified: 000059 (dataset)
 modified: 000059/.dandi/assets.json (file)
 modified: 000059/dandiset.yaml (file)
 modified: 000060 (dataset)
 modified: 000060/.dandi/assets.json (file)
 modified: 000060/dandiset.yaml (file)
 modified: 000061 (dataset)
 modified: 000061/.dandi/assets.json (file)
 modified: 000061/dandiset.yaml (file)
 modified: 000063 (dataset)
 modified: 000063/dandiset.yaml (file)
 modified: 000064 (dataset)
 modified: 000064/.dandi/assets.json (file)
 modified: 000064/dandiset.yaml (file)
 modified: 000065 (dataset)
 modified: 000065/.dandi/assets.json (file)
 modified: 000065/dandiset.yaml (file)
 modified: 000066 (dataset)
 modified: 000066/.dandi/assets.json (file)
 modified: 000066/dandiset.yaml (file)
 modified: 000067 (dataset)
 modified: 000067/.dandi/assets.json (file)
 modified: 000067/dandiset.yaml (file)
```
</details>

<details>
<summary>and for that modified file we do get a nice new url to blobs</summary> 

```shell
(dandisets) dandi@drogon:/mnt/backup/dandi/dandisets/000053/sub-npI1$ git annex whereis sub-npI1_ses-20190413_behavior+ecephys.nwb
whereis sub-npI1_ses-20190413_behavior+ecephys.nwb (2 copies) 
        00000000-0000-0000-0000-000000000001 -- web
        336ce2df-0304-48a8-aa71-c7220933003c -- dandi@drogon:/mnt/backup/dandi/dandisets/000053 [here]

  web: https://dandiarchive.s3.amazonaws.com/blobs/a62/ecf/a62ecfe2-01e9-4409-9ee8-d17ed38ed6f2?versionId=0RcIMnH.nAgv7BZ2EWYIRdXHp6mjSPFw
ok
```
</details>

so I think it should be good to have this merged -- time to take from the draft?

we will need a follow up script or some kind of mode to populate with `/blobs/` URLs and remove old girder ones, let's take/continue in #34 for that.

**Comment by yarikoptic** [comment]
Let's proceed with this one, thank you @jwodder!

**Pull request merged**
