### PR TITLE
Set web URL priorities when initting a dataset

### LINKED ISSUE #320: in dandisets and dandizarrs establish remote for web URLs with higher cost
see http://git-annex.branchable.com/todo/Allow_for_URLs_prioritization_WITHIN___40__web__41___remote/#comment-915b0a31a1329226a6d431260326bd3d for more information etc. [10.20221212-103-gcfaae7e93](https://git.kitenet.net/index.cgi/git-annex.git/commit/?id=cfaae7e931c72b482f2eefb2d17eaf04b8eee81d) implements adding "sameas" remotes which would state higher cost for API URLs.

We would need to initremote in all new dandisets and dandizarrs and have a helper to tune all already existing dandisets/dandizarrs

### PR DESCRIPTION
**Pull request by jwodder**
Closes #320.

Blocked by the lack of git-annex 10.20230126 in conda-forge.

### CODE REVIEW

**Comment by yarikoptic** [comment]
related issue: https://github.com/conda-forge/git-annex-feedstock/issues/152  . I will touch base with @notestaff but we might need to help there. The tricky part is that "nodep" build for which I forgot the "workflow" to get it updated.

**Comment by yarikoptic** [comment]
tests fail since need recent git-annex release.  I will build one now for neurodebian.

**Comment by yarikoptic** [comment]
now installs most recent one but still fails
```
2023-02-01T16:29:03.3153839Z Preparing to unpack .../074-git-annex-standalone_10.20230126-1~ndall+1_amd64.deb ...
2023-02-01T16:29:03.3165031Z Unpacking git-annex-standalone (10.20230126-1~ndall+1) ...
```
I do not see why ... is there stderr ?

**Comment by jwodder** [comment]
@yarikoptic The current failures appear to be due to "bogus format in GIT_CONFIG_PARAMETERS".  For the record, that envvar is set as follows when running `datalad create`:

https://github.com/dandi/dandisets/blob/199dbbfc495c07f4f74c1f617bed6d8dce7768d6/tools/backups2datalad/adataset.py#L73

**Comment by yarikoptic** [comment]
Iirc, this is happening with standalone build when system git is too old, I will later push a try to fix workaround which would export assisted PATH...

**Comment by yarikoptic** [comment]
yippee -- it is green, I thought to just uninstall git-annex in `dandisets` conda  and proceed BUT `datalad` depends on git-annex so I can't `uninstall` it :-/ so - although ready, we should wait until we manage to build fresh git-annex in conda-forge.

**Comment by yarikoptic** [comment]
FWIW -- we have (standalone) build of recent git-annex installed already in new `dandisets-2` environment. Let's proceed!  I will manually go through existing ones with e.g.

```
 for d in 000*; do  git -C $d annex initremote --sameas=web dandiapi type=web urlinclude='*//api.dandiarchive.org/*' cost=300; done
```

and now through dandizarrs

**Comment by yarikoptic** [comment]
note -- I will also need to push git-annex branch to github... should have added to the loop

**Pull request merged**
