### PR TITLE
populate: Actually run commands inside datasets

### LINKED ISSUE #132: not needed warning + seems does not move the file but copies?
did manual run after the merge of #103 

<details>
<summary>protocol of the run</summary> 

```shell
(dandisets) dandi@drogon:/mnt/backup/dandi/dandisets$ flock -E 0 -e -n /home/dandi/.run/backup2datalad-cron.lock bash -c '/mnt/backup/dandi/dandisets/tools/backups2datalad-cron'
>> python -m tools.backups2datalad -l WARNING -J 5 --target /mnt/backup/dandi/dandisets update-from-backup --backup-remote dandi-dandisets-dropbox --gh-org dandisets -e '000108$'


2022-03-03T16:32:13-0500 [WARNING ] backups2datalad sub-despereaux/sub-despereaux_ses-despereaux-12_behavior+ecephys+image.nwb: Not in backup remote dandi-dandisets-dropbox
2022-03-03T16:32:13-0500 [WARNING ] backups2datalad sub-despereaux/sub-despereaux_ses-despereaux-14_behavior+ecephys.nwb: Not in backup remote dandi-dandisets-dropbox
2022-03-03T16:32:13-0500 [WARNING ] backups2datalad sub-despereaux/sub-despereaux_ses-despereaux-07_behavior+ecephys.nwb: Not in backup remote dandi-dandisets-dropbox
2022-03-03T16:32:13-0500 [WARNING ] backups2datalad sub-despereaux/sub-despereaux_ses-despereaux-10_behavior+ecephys.nwb: Not in backup remote dandi-dandisets-dropbox
2022-03-03T16:32:13-0500 [WARNING ] backups2datalad sub-despereaux/sub-despereaux_ses-despereaux-11_behavior+ecephys+image.nwb: Not in backup remote dandi-dandisets-dropbox
2022-03-03T16:32:13-0500 [WARNING ] backups2datalad sub-despereaux/sub-despereaux_ses-despereaux-05_behavior+ecephys+image.nwb: Not in backup remote dandi-dandisets-dropbox
2022-03-03T16:32:13-0500 [WARNING ] backups2datalad sub-despereaux/sub-despereaux_ses-despereaux-06_behavior+ecephys.nwb: Not in backup remote dandi-dandisets-dropbox
2022-03-03T16:32:13-0500 [WARNING ] backups2datalad sub-montague/sub-montague_ses-montague-13_behavior+ecephys.nwb: Not in backup remote dandi-dandisets-dropbox
2022-03-03T16:32:13-0500 [WARNING ] backups2datalad sub-montague/sub-montague_ses-montague-09_behavior+ecephys.nwb: Not in backup remote dandi-dandisets-dropbox
2022-03-03T16:32:13-0500 [WARNING ] backups2datalad sub-despereaux/sub-despereaux_ses-despereaux-04_behavior+ecephys+image.nwb: Not in backup remote dandi-dandisets-dropbox
2022-03-03T16:32:13-0500 [WARNING ] backups2datalad sub-montague/sub-montague_ses-montague-04_behavior+ecephys.nwb: Not in backup remote dandi-dandisets-dropbox
whereis: 25 failed
2022-03-03T16:32:15-0500 [WARNING ] backups2datalad git-annex whereis command exited with return code 1
whereis: 116 failed
2022-03-03T21:52:37-0500 [WARNING ] backups2datalad git-annex whereis command exited with return code 1
whereis: 263 failed
2022-03-03T21:54:22-0500 [WARNING ] backups2datalad git-annex whereis command exited with return code 1
Switched to a new branch 'release-0.220303.1653'
Switched to branch 'draft'
Your branch is ahead of 'github/draft' by 1 commit.
  (use "git push" to publish your local commits)
Deleted branch release-0.220303.1653 (was 836e34b).
To github.com:dandisets/000221.git
 * [new tag]         0.220303.1653 -> 0.220303.1653
Merge made by the 'ours' strategy.
Already up to date.
publish(ok): . (dataset) [refs/heads/draft->github:refs/heads/draft 92078de..3781f81]
> '[' -s .git/tmp/stderr ']'
> echo 'There was stderr from backup/datalad invocations:'
There was stderr from backup/datalad invocations:
> cat .git/tmp/stderr
> eval python -m tools.backups2datalad -l WARNING -J 5 --target /mnt/backup/dandi/dandisets update-from-backup --backup-remote dandi-dandisets-dropbox --gh-org dandisets -e '000108$' ''
> grep -v 'nothing to save, working tree clean'
> python -m tools.backups2datalad -l WARNING -J 5 --target /mnt/backup/dandi/dandisets populate dandi-dandisets-dropbox
> git pull
From github.com:dandi/dandisets
 * [new branch]      gh-129     -> github/gh-129
> datalad push -J 5
> git diff --exit-code

```
</details>

has a number of warnings like

```
2022-03-03T16:32:13-0500 [WARNING ] backups2datalad sub-despereaux/sub-despereaux_ses-despereaux-14_behavior+ecephys.nwb: Not in backup remote dandi-dandisets-dropbox
...
whereis: 25 failed
2022-03-03T16:32:15-0500 [WARNING ] backups2datalad git-annex whereis command exited with return code 1
```

which I think should not be a warning if we are expecting that new assets would not yet be in the backup.  

And `populate dandi-dandisets-dropbox` produced no output but running `whereis` after the script was done on a sample file showed that it is already in dropbox:

```
(dandisets) dandi@drogon:/mnt/backup/dandi/dandisets$ git -C 000115 annex whereis $PWD/*/sub-despereaux/sub-despereaux_ses-despereaux-14_behavior+ecephys.nwb
whereis sub-despereaux/sub-despereaux_ses-despereaux-14_behavior+ecephys.nwb (2 copies)
        00000000-0000-0000-0000-000000000001 -- web
        a009106d-425c-4797-9450-e835f238f67a -- dandi@drogon:/mnt/backup/dandi/dandisets/000115 [here]

  The following untrusted locations may also have copies:
        727f466f-60c3-4778-90b2-b2332856c2f8 -- [dandi-dandisets-dropbox]

  web: https://api.dandiarchive.org/api/assets/daf68ce2-43ba-4b83-93f2-084a043d116b/download/
  web: https://dandiarchive.s3.amazonaws.com/blobs/d24/1f1/d241f1a5-1bb1-47d5-8a64-b42e27c7bee6?versionId=gkfzuPzoNVwUgDFrBl25G7jVoyQiEPnu
ok
```
which made sense (was not in backup, was transferred to backup), but it still had content locally:

```shell
(dandisets) dandi@drogon:/mnt/backup/dandi/dandisets$ ls -lL $PWD/*/sub-despereaux/sub-despereaux_ses-despereaux-14_behavior+ecephys.nwb
-r--r--r-- 1 dandi dandi 218539827424 Feb 27 08:02 /mnt/backup/dandi/dandisets/000115/sub-despereaux/sub-despereaux_ses-despereaux-14_behavior+ecephys.nwb
```
which I think should not happen -- content should be moved , not copied.  

ATM I am doing the 2nd identical rerun to see what I get in output (it is in screen under dandi user)

@jwodder please 
- downgrade WARNING to INFO about missing in backup within `update-from-backup`
- make it `move` not `copy` to backup (otherwise we would keep filling up)

### PR DESCRIPTION
**Pull request by jwodder**
(Hopefully) fixes #132.

### CODE REVIEW

**Comment by yarikoptic** [comment]
so we do not have any tests for this part of the code to ensure that it gets desired effect?

**Comment by jwodder** [comment]
@yarikoptic No, that would require setting up a separate remote somehow.

**Comment by yarikoptic** [comment]
setting up a separate remote is very simple -- it could be a regular `git` remote or better in this case annex special remote, e.g. a `type=directory` in some temp path. See `git annex initremote`  etc

**Comment by jwodder** [comment]
@yarikoptic Rewriting the code to support remotes for testing is a non-trivial undertaking that would just delay this fix from getting merged.  I suggest merging this PR as-is as soon as possible and creating a separate issue for adding tests to `populate`.

**Comment by yarikoptic** [comment]
ok, let's proceed then

**Comment by yarikoptic** [comment]
thank you @jwodder

**Pull request merged**
