### PR TITLE
Don't expect JSON in /publish/ response

### PR DESCRIPTION
**Pull request by jwodder**

### CODE REVIEW

**Comment by yarikoptic** [comment]
FWIW: I was testing locally and confirming that resolved errorring out test_backups2datalad/test_core.py::test_4 on empty json but then it finally errorred out with

```
E       ValueError: Dandiset 204689 is Pending: {
E           "asset_validation_errors": [],
E           "version_validation_errors": []
E       }
```

CI finished with similar errors here. Meanwhile will disable cron job to avoid errors

**Comment by jwodder** [comment]
@yarikoptic Errors with publishing (either due to the lack of this PR or in the tests) don't affect the actual running of the backup script, as `/publish/` is only called in tests to prepare Dandisets with multiple versions.

**Comment by yarikoptic** [comment]
ah, right -- reenabling CRON.

**Comment by yarikoptic** [comment]
do you see how to finish this one up  so code gets green again and I could test my changes the #278?

**Comment by jwodder** [comment]
@yarikoptic If the tests don't pass after rerunning, we may have to file a bug report with the Archive saying that validation is taking too long.

**Comment by yarikoptic** [comment]
hm... that is validation on the https://gui-staging.dandiarchive.org/ instance right? if we end up failing -- indeed please file an issue with the archive.

**Comment by yarikoptic** [comment]
Hmm ok, passed

**Pull request merged**
