### PR TITLE
BF: use "git commit -a" instead of "datalad save" for when saving updated state

### PR DESCRIPTION
**Pull request by yarikoptic**
I hope that we have everything already staged so it should just work, but it might be that we would need to add some "git rm" instead of just plain "unlink" if files were removed etc... to be seen!

An alterantive would be to do  datalad save  followed by git commit --amend -a reusing the message etc, but should be done carefully since there might have been no commit so we have to not use --amend...

Hope is that it would address the 2nd part of the
https://github.com/dandi/dandisets/issues/276

### CODE REVIEW

**Comment by yarikoptic** [comment]
so it is still dirty after commit, would need more checking or just coming up with a different solution :-/

**Comment by yarikoptic** [comment]
@jwodder please have a look at what files we forgot to add for the commit to see if we could resolve it cuz good old explicit git annex add if anything else needs to be added (may be even we could just `annex add .` before commit?). I don't think we will find a better solution within datalad for this problem.

**Comment by jwodder** [comment]
@yarikoptic I believe I've completed this PR.  The tests pass locally, but the CI isn't starting for some reason.

**Comment by yarikoptic** [comment]
Hmm, I don't know either. May be rewrite the last commit once more some time - may be there was some intermittent GitHub gotcha. I also took from draft

**Comment by jwodder** [comment]
@yarikoptic The tests have run & passed now.

**Comment by yarikoptic** [comment]
Great, thanks! Let's get it in then

**Pull request merged**
