### PR TITLE
Manually `git add` files for which addurl fails with code 123

### LINKED ISSUE #168: some assets aren't addurl'ed nicely
kept rerunning this one while manually fixing up zarrs , some code fixes pushed directly etc and arrived at

```
(base) dandi@drogon:/mnt/backup/dandi/dandisets$ bash tools/backups2datalad-108
>> python -m tools.backups2datalad -l WARNING -J 5 --target . update-from-backup --zarr-target /mnt/backup/dandi/dandizarrs --backup-remote dandi-dandisets-dropbox --zarr-backup-remote dandi-dandizarrs-dropbox --gh-org dandisets --zarr-gh-org dandizarrs 000108
A newer version (0.40.0) of dandi/dandi-cli is available. You are using 0.36.0
...
create_sibling_github(ok): [sibling repository 'github' created at https://github.com/dandizarrs/dac9b7da-b880-47a2-aa55-53888db8443a]
configure-sibling(ok): . (sibling)
action summary:
  configure-sibling (ok: 1)
  create_sibling_github (ok: 1)
2022-05-31T15:32:02-0400 [ERROR   ] backups2datalad sub-MITU01/ses-20220311h10m19s37/micr/sub-MITU01_ses-20220311h10m19s37_sample-22_stain-LEC_run-1_chunk-4_SPIM.json: download failed: git-annex: user error (xargs ["-0","git","--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","filter.annex.smudge=","-c","filter.annex.clean=","-c","filter.annex.process=","add","-f","--"] exited 123)
2022-05-31T15:32:03-0400 [ERROR   ] backups2datalad sub-MITU01/ses-20220311h10m19s37/micr/sub-MITU01_ses-20220311h10m19s37_sample-22_stain-LEC_run-1_chunk-7_SPIM.json: download failed: git-annex: user error (xargs ["-0","git","--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","filter.annex.smudge=","-c","filter.annex.clean=","-c","filter.annex.process=","add","-f","--"] exited 123)
...
```

with a bunch of such errors but not for all files... grepping the lengthy (31GB! BTRFS compressed to 24%; shouldn't forge to clean up at some point) log brings

```
(dandisets) dandi@drogon:/mnt/backup/dandi/dandisets/000108/.git/dandi/logs$ grep sample-22_stain-LEC_run-1_chunk-4_SPIM.json sync-20220531185804Z-1923684.log
2022-05-31T15:32:00-0400 [INFO    ] backups2datalad sub-MITU01/ses-20220311h10m19s37/micr/sub-MITU01_ses-20220311h10m19s37_sample-22_stain-LEC_run-1_chunk-4_SPIM.json: Syncing
2022-05-31T15:32:00-0400 [INFO    ] backups2datalad sub-MITU01/ses-20220311h10m19s37/micr/sub-MITU01_ses-20220311h10m19s37_sample-22_stain-LEC_run-1_chunk-4_SPIM.json: Not in dataset; will add
2022-05-31T15:32:00-0400 [DEBUG   ] backups2datalad sub-MITU01/ses-20220311h10m19s37/micr/sub-MITU01_ses-20220311h10m19s37_sample-22_stain-LEC_run-1_chunk-4_SPIM.json: Fetching bucket URL
2022-05-31T15:32:00-0400 [DEBUG   ] backups2datalad sub-MITU01/ses-20220311h10m19s37/micr/sub-MITU01_ses-20220311h10m19s37_sample-22_stain-LEC_run-1_chunk-4_SPIM.json: About to query S3
2022-05-31T15:32:00-0400 [DEBUG   ] backups2datalad sub-MITU01/ses-20220311h10m19s37/micr/sub-MITU01_ses-20220311h10m19s37_sample-22_stain-LEC_run-1_chunk-4_SPIM.json: Got bucket URL
2022-05-31T15:32:00-0400 [INFO    ] backups2datalad sub-MITU01/ses-20220311h10m19s37/micr/sub-MITU01_ses-20220311h10m19s37_sample-22_stain-LEC_run-1_chunk-4_SPIM.json: File is text; sending off for download from https://dandiarchive.s3.amazonaws.com/blobs/59f/875/59f87539-3dd7-4a9d-87b3-f3623c9189ce?versionId=8tNAHjGgIE9mP8wMNY_y65O3sBrH1PTu
2022-05-31T15:32:00-0400 [INFO    ] backups2datalad sub-MITU01/ses-20220311h10m19s37/micr/sub-MITU01_ses-20220311h10m19s37_sample-22_stain-LEC_run-1_chunk-4_SPIM.json: Downloading from https://dandiarchive.s3.amazonaws.com/blobs/59f/875/59f87539-3dd7-4a9d-87b3-f3623c9189ce?versionId=8tNAHjGgIE9mP8wMNY_y65O3sBrH1PTu
2022-05-31T15:32:00-0400 [TRACE   ] backups2datalad Sending to addurl command: 'https://dandiarchive.s3.amazonaws.com/blobs/59f/875/59f87539-3dd7-4a9d-87b3-f3623c9189ce?versionId=8tNAHjGgIE9mP8wMNY_y65O3sBrH1PTu sub-MITU01/ses-20220311h10m19s37/micr/sub-MITU01_ses-20220311h10m19s37_sample-22_stain-LEC_run-1_chunk-4_SPIM.json\n'
2022-05-31T15:32:02-0400 [TRACE   ] backups2datalad Decoded line from addurl command: '{"command":"addurl","note":"to sub-MITU01/ses-20220311h10m19s37/micr/sub-MITU01_ses-20220311h10m19s37_sample-22_stain-LEC_run-1_chunk-4_SPIM.json\\nnon-large file; adding content to git repository","success":false,"input":["https://dandiarchive.s3.amazonaws.com/blobs/59f/875/59f87539-3dd7-4a9d-87b3-f3623c9189ce?versionId=8tNAHjGgIE9mP8wMNY_y65O3sBrH1PTu sub-MITU01/ses-20220311h10m19s37/micr/sub-MITU01_ses-20220311h10m19s37_sample-22_stain-LEC_run-1_chunk-4_SPIM.json"],"error-messages":["git-annex: user error (xargs [\\"-0\\",\\"git\\",\\"--git-dir=.git\\",\\"--work-tree=.\\",\\"--literal-pathspecs\\",\\"-c\\",\\"filter.annex.smudge=\\",\\"-c\\",\\"filter.annex.clean=\\",\\"-c\\",\\"filter.annex.process=\\",\\"add\\",\\"-f\\",\\"--\\"] exited 123)"],"file":"sub-MITU01/ses-20220311h10m19s37/micr/sub-MITU01_ses-20220311h10m19s37_sample-22_stain-LEC_run-1_chunk-4_SPIM.json"}\n'
2022-05-31T15:32:02-0400 [ERROR   ] backups2datalad sub-MITU01/ses-20220311h10m19s37/micr/sub-MITU01_ses-20220311h10m19s37_sample-22_stain-LEC_run-1_chunk-4_SPIM.json: download failed: git-annex: user error (xargs ["-0","git","--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","filter.annex.smudge=","-c","filter.annex.clean=","-c","filter.annex.process=","add","-f","--"] exited 123)

```

not sure what it is about

if I try to redo manually it sure thing fails since file is there first but then if I remove, addurl works just fine:

```
(dandisets) dandi@drogon:/mnt/backup/dandi/dandisets/000108$ echo 'https://dandiarchive.s3.amazonaws.com/blobs/59f/875/59f87539-3dd7-4a9d-87b3-f3623c9189ce?versionId=8tNAHjGgIE9mP8wMNY_y65O3sBrH1PTu sub-MITU01/ses-20220311h10m19s37/micr/sub-MITU01_ses-20220311h10m19s37_sample-22_stain-LEC_run-1_chunk-4_SPIM.json' | git annex addurl --batch  --with-files --json --json-error-messages
{"command":"addurl","success":false,"input":["https://dandiarchive.s3.amazonaws.com/blobs/59f/875/59f87539-3dd7-4a9d-87b3-f3623c9189ce?versionId=8tNAHjGgIE9mP8wMNY_y65O3sBrH1PTu sub-MITU01/ses-20220311h10m19s37/micr/sub-MITU01_ses-20220311h10m19s37_sample-22_stain-LEC_run-1_chunk-4_SPIM.json"],"error-messages":["  sub-MITU01/ses-20220311h10m19s37/micr/sub-MITU01_ses-20220311h10m19s37_sample-22_stain-LEC_run-1_chunk-4_SPIM.json already exists; not overwriting"],"file":"sub-MITU01/ses-20220311h10m19s37/micr/sub-MITU01_ses-20220311h10m19s37_sample-22_stain-LEC_run-1_chunk-4_SPIM.json"}
addurl: 1 failed

(dandisets) dandi@drogon:/mnt/backup/dandi/dandisets/000108$ git status sub-MITU01/ses-20220311h10m19s37/micr/sub-MITU01_ses-20220311h10m19s37_sample-22_stain-LEC_run-1_chunk-4_SPIM.json
On branch draft
Your branch is up to date with 'github/draft'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        sub-MITU01/ses-20220311h10m19s37/micr/sub-MITU01_ses-20220311h10m19s37_sample-22_stain-LEC_run-1_chunk-4_SPIM.json

nothing added to commit but untracked files present (use "git add" to track)

(dandisets) dandi@drogon:/mnt/backup/dandi/dandisets/000108$ rm sub-MITU01/ses-20220311h10m19s37/micr/sub-MITU01_ses-20220311h10m19s37_sample-22_stain-LEC_run-1_chunk-4_SPIM.json

(dandisets) dandi@drogon:/mnt/backup/dandi/dandisets/000108$ echo 'https://dandiarchive.s3.amazonaws.com/blobs/59f/875/59f87539-3dd7-4a9d-87b3-f3623c9189ce?versionId=8tNAHjGgIE9mP8wMNY_y65O3sBrH1PTu sub-MITU01/ses-20220311h10m19s37/micr/sub-MITU01_ses-20220311h10m19s37_sample-22_stain-LEC_run-1_chunk-4_SPIM.json' | git annex addurl --batch  --with-files --json --json-error-messages
{"command":"addurl","note":"to sub-MITU01/ses-20220311h10m19s37/micr/sub-MITU01_ses-20220311h10m19s37_sample-22_stain-LEC_run-1_chunk-4_SPIM.json\nnon-large file; adding content to git repository","success":true,"input":["https://dandiarchive.s3.amazonaws.com/blobs/59f/875/59f87539-3dd7-4a9d-87b3-f3623c9189ce?versionId=8tNAHjGgIE9mP8wMNY_y65O3sBrH1PTu sub-MITU01/ses-20220311h10m19s37/micr/sub-MITU01_ses-20220311h10m19s37_sample-22_stain-LEC_run-1_chunk-4_SPIM.json"],"error-messages":[],"file":"sub-MITU01/ses-20220311h10m19s37/micr/sub-MITU01_ses-20220311h10m19s37_sample-22_stain-LEC_run-1_chunk-4_SPIM.json"}
(dandisets) dandi@drogon:/mnt/backup/dandi/dandisets/000108$ echo $?
0
```

<details>
<summary>altogether some files were added just fine and some not and I don't see why</summary> 

```shell
(dandisets) dandi@drogon:/mnt/backup/dandi/dandisets/000108$ git status sub-MITU01/ses-20220311h10m19s37/micr/
On branch draft
Your branch is up to date with 'github/draft'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        new file:   sub-MITU01/ses-20220311h10m19s37/micr/sub-MITU01_sample-22_photo.jpg
        new file:   sub-MITU01/ses-20220311h10m19s37/micr/sub-MITU01_ses-20220311h10m19s37_sample-22_stain-LEC_run-1_chunk-4_SPIM.json
        new file:   sub-MITU01/ses-20220311h10m19s37/micr/sub-MITU01_ses-20220311h10m19s37_sample-22_stain-LEC_run-1_chunk-5_SPIM.json
        new file:   sub-MITU01/ses-20220311h10m19s37/micr/sub-MITU01_ses-20220311h10m19s37_sample-22_stain-LEC_run-1_chunk-6_SPIM.json
        new file:   sub-MITU01/ses-20220311h10m19s37/micr/sub-MITU01_ses-20220311h10m19s37_sample-22_stain-NN_run-1_chunk-2_SPIM.json
        new file:   sub-MITU01/ses-20220311h10m19s37/micr/sub-MITU01_ses-20220311h10m19s37_sample-22_stain-NN_run-1_chunk-3_SPIM.json
        new file:   sub-MITU01/ses-20220311h10m19s37/micr/sub-MITU01_ses-20220311h10m19s37_sample-22_stain-NN_run-1_chunk-8_SPIM.json
        new file:   sub-MITU01/ses-20220311h10m19s37/micr/sub-MITU01_ses-20220311h10m19s37_sample-22_stain-YO_run-1_chunk-2_SPIM.json
        new file:   sub-MITU01/ses-20220311h10m19s37/micr/sub-MITU01_ses-20220311h10m19s37_sample-22_stain-YO_run-1_chunk-3_SPIM.json
        new file:   sub-MITU01/ses-20220311h10m19s37/micr/sub-MITU01_ses-20220311h10m19s37_sample-22_stain-YO_run-1_chunk-4_SPIM.json
        new file:   sub-MITU01/ses-20220311h10m19s37/micr/sub-MITU01_ses-20220311h10m19s37_sample-22_stain-YO_run-1_chunk-8_SPIM.json

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        sub-MITU01/ses-20220311h10m19s37/micr/sub-MITU01_ses-20220311h10m19s37_sample-22_stain-LEC_run-1_chunk-1_SPIM.json
        sub-MITU01/ses-20220311h10m19s37/micr/sub-MITU01_ses-20220311h10m19s37_sample-22_stain-LEC_run-1_chunk-2_SPIM.json
        sub-MITU01/ses-20220311h10m19s37/micr/sub-MITU01_ses-20220311h10m19s37_sample-22_stain-LEC_run-1_chunk-3_SPIM.json
        sub-MITU01/ses-20220311h10m19s37/micr/sub-MITU01_ses-20220311h10m19s37_sample-22_stain-LEC_run-1_chunk-7_SPIM.json
        sub-MITU01/ses-20220311h10m19s37/micr/sub-MITU01_ses-20220311h10m19s37_sample-22_stain-LEC_run-1_chunk-8_SPIM.json
        sub-MITU01/ses-20220311h10m19s37/micr/sub-MITU01_ses-20220311h10m19s37_sample-22_stain-NN_run-1_chunk-1_SPIM.json
        sub-MITU01/ses-20220311h10m19s37/micr/sub-MITU01_ses-20220311h10m19s37_sample-22_stain-NN_run-1_chunk-4_SPIM.json
        sub-MITU01/ses-20220311h10m19s37/micr/sub-MITU01_ses-20220311h10m19s37_sample-22_stain-NN_run-1_chunk-5_SPIM.json
        sub-MITU01/ses-20220311h10m19s37/micr/sub-MITU01_ses-20220311h10m19s37_sample-22_stain-NN_run-1_chunk-6_SPIM.json
        sub-MITU01/ses-20220311h10m19s37/micr/sub-MITU01_ses-20220311h10m19s37_sample-22_stain-NN_run-1_chunk-7_SPIM.json
        sub-MITU01/ses-20220311h10m19s37/micr/sub-MITU01_ses-20220311h10m19s37_sample-22_stain-YO_run-1_chunk-1_SPIM.json
        sub-MITU01/ses-20220311h10m19s37/micr/sub-MITU01_ses-20220311h10m19s37_sample-22_stain-YO_run-1_chunk-5_SPIM.json
        sub-MITU01/ses-20220311h10m19s37/micr/sub-MITU01_ses-20220311h10m19s37_sample-22_stain-YO_run-1_chunk-6_SPIM.json
        sub-MITU01/ses-20220311h10m19s37/micr/sub-MITU01_ses-20220311h10m19s37_sample-22_stain-YO_run-1_chunk-7_SPIM.json

```
</details>
and I think it happens consistently --  must be something special about those files or urls.  Any ideas @jwodder ??

### PR DESCRIPTION
**Pull request by jwodder**
Closes #168.

### CODE REVIEW

**Comment by yarikoptic** [comment]
looks kosher to me but CI says there is now one more commit or smth and fails

**Comment by jwodder** [comment]
@yarikoptic As with #198, I believe the CI failure is due to the server taking a while to update Dandiset metadata with the size info for Zarrs.

**Comment by jwodder** [comment]
@yarikoptic #200 should take care of the test failures.

**Comment by yarikoptic** [comment]
coolio thanks! Let's proceed then.

**Pull request merged**
